import {
  DOUGH_LIGHT_KEY,
  DOUGH_LIGHT_VALUE,
  DOUGH_LARGE_KEY,
  DOUGH_LARGE_VALUE,
} from '@/common/const.js';

export default {
  [DOUGH_LIGHT_KEY]: DOUGH_LIGHT_VALUE,
  [DOUGH_LARGE_KEY]: DOUGH_LARGE_VALUE,
};
