export const SET_LOADING = "SET_LOADING";

export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_USER = "SET_USER";

export const SET_BUILDER_INITIAL_DATA = "SET_BUILDER_INITIAL_DATA";
export const SET_DOUGH = "SET_DOUGH";
export const SET_SAUCE = "SET_SAUCE";
export const SET_SIZE = "SET_SIZE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_PIZZA_NAME = "SET_PIZZA_NAME";
export const NORMALIZE_BUILDER = "NORMALIZE_BUILDER";
export const CHANGE_INGREDIENT_QUANTITY = "CHANGE_INGREDIENT_QUANTITY";
export const RESET_CURRENT_PIZZA = "RESET_CURRENT_PIZZA";
export const EDIT_PIZZA = "EDIT_PIZZA";

export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const NORMALIZE_MISC = "NORMALIZE_MISC";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const UPDATE_PRODUCT_PRICE = "UPDATE_PRODUCT_PRICE";
export const CHANGE_MISC_QUANTITY = "CHANGE_MISC_QUANTITY";
export const SET_MISC = "SET_MISC";
export const SET_PHONE = "SET_PHONE";
export const SET_ADDRESS = "SET_ADDRESS";
export const RESET_CART = "RESET_CART";

export const SET_ORDERS = "SET_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";
export const REPEAT_ORDER = "REPEAT_ORDER";
export const NORMALIZE_ORDERS = "NORMALIZE_ORDERS";

export const SET_ADDRESSES = "SET_ADDRESSES";
export const SET_CART_ADDRESS_ENTITY = "SET_CART_ADDRESS_ENTITY";
export const SET_PROFILE_ADDRESS_ENTITY = "SET_PROFILE_ADDRESS_ENTITY";
export const RESET_PROFILE_ADDRESS = "RESET_PROFILE_ADDRESS";
