export const SET_BUILDER = "SET_BUILDER";
export const ADD_BUILDER_ADDITIONAL_DATA = "ADD_BUILDER_ADDITIONAL_DATA";
export const SET_PIZZA_ENTITY = "SET_PIZZA_ENTITY";
export const CHANGE_INGREDIENT_QUANTITY = "CHANGE_INGREDIENT_QUANTITY";
export const ADD_INGREDIENT_QUANTITY = "ADD_INGREDIENT_QUANTITY";
export const SELECT_PIZZA_ENTITY = "SELECT_PIZZA_ENTITY";
export const ADD_INGREDIENTS_IN_PIZZA = "ADD_INGREDIENTS_IN_PIZZA";

export const ADD_CART_ENTITY = "ADD_CART_ENTITY";
export const ADD_MISC_ADDITIONAL_DATA = "ADD_MISC_ADDITIONAL_DATA";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const UPDATE_PRODUCT_PRICE = "UPDATE_PRODUCT_PRICE";
export const CHANGE_MISC_QUANTITY = "CHANGE_MISC_QUANTITY";

export const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
